### ISSUE TITLE
Creating the initial env

### ISSUE THREAD

**Issue by mickyals** [Asparagus15/GaussianShader#27]
Hi

my group and I have been trying for a few days to create the environment with all the necessary packages and dependencies but are stuck at the ` pip install submodules/diff-gaussian-rasterization` step. I continuously receive the error ` error: [Errno 2] No such file or directory: '/usr/local/cuda/bin/nvcc': '/usr/local/cuda/bin/nvcc'` but the `nvcc` file is location within that directory. 

```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_18:49:52_PDT_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0

```

On my end, i am using WSL. If you could provide any tips and advice for getting the environment set up, it would be greatly appreciated.

**Comment by nyy618** [comment]
I have encountered this problem too. This error seems to be with 3DGS. You should check whether you have different versions of cuda in your computer. I just reinstalled cuda to solve this problem.

**Comment by mickyals** [comment]
figured it out, thank you
