### ISSUE TITLE
The evaluation results in the paper seem to differ

### ISSUE THREAD

**Issue by badlooop** [Asparagus15/GaussianShader#4]
First of all, I would like to extend my sincere gratitude for contributing such an excellent method to the industry! 

However, I noticed a discrepancy between the test results of Ref-NeRF and those presented in the original Ref-NeRF paper while reading your study. Could you please clarify if any specific factors might have led to these differences?

![refnerf-ori](https://github.com/Asparagus15/GaussianShader/assets/12500298/7a03f618-d099-43b7-826d-bca64198b2aa)
![gaussianshader](https://github.com/Asparagus15/GaussianShader/assets/12500298/8aef6e8d-ccdf-4051-87c4-eec25c6b60dc)

**Comment by Asparagus15** [comment]
We explain the reason in the article: 

>  For Ref-NeRF, ENVIDR, and 3D Gaussian Splatting, we retrain them using their official codes and obtain all their results
from our retrained models. Other works’ results are imported from their original papers.
