### ISSUE TITLE
The problem of training:  No such file or directory: 'data/irrmaps/bsdf_256_256.bin'

### ISSUE THREAD

**Issue by cuijh26** [Asparagus15/GaussianShader#5]
I follow the README, and try to train, but encounter a problem. It seem that it couldn't find a file 
![image](https://github.com/Asparagus15/GaussianShader/assets/90942334/7258ac50-c28d-404f-aef4-16925ece6fcd)

**Comment by Asparagus15** [comment]
Thanks for the reminder, I have uploaded the required files.
