### ISSUE TITLE
Is delta_normal_loss correct ? 

### ISSUE THREAD

**Issue by gs14iitbbs** [Asparagus15/GaussianShader#8]
I think in delta_normal_loss() function, it should be  -->  l = delta_normal.permute(1,2,0).reshape(-1,3).norm(dim=-1)
@Asparagus15 

> https://github.com/Asparagus15/GaussianShader/blob/28e4f89198e19c0cabee82369118923d9bd41bba/utils/loss_utils.py#L116

**Comment by Asparagus15** [comment]
Thanks for reminding, I have fixed it in the latest update.
